include: package:flutter_lints/flutter.yaml

analyzer:
  # errors:
  # mixin_inherits_from_not_object: ignore

linter:
  rules:
    # public_member_api_docs: false
    prefer_const_constructors: false
    prefer_relative_imports: true
    # avoid_function_literals_in_foreach_class: false
