name: financial_controlee_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  json_serializable: ^5.0.2
  firebase_auth: ^3.1.0
  hasura_connect: ^3.0.4
  firebase_core: ^1.6.0
  get: 4.3.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.1.0
  font_awesome_flutter: ^9.1.0
  get_storage: ^2.0.3
  intl: ^0.17.0
  dio: ^4.0.0
  form_field_validator: ^1.1.0
  currency_text_input_formatter: ^2.1.3
  flutter_easyloading: ^3.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
