name: financialcontroleeapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  smooth_page_indicator: ^0.2.1
  intl: ^0.17.0
  money2: ^2.0.2
  flutter_login_facebook: ^0.5.0
  progress_dialog: ^1.2.4
  loading_animations: ^2.1.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^2.0.0
  hasura_connect: ^3.0.0
  circular_check_box: ^1.0.4
  percent_indicator: ^2.1.9+1
  adaptive_dialog: ^0.10.0+5
  firebase_analytics: ^7.1.0
  firebase_core: ^1.0.0
  flutter_animation_progress_bar: ^1.0.6
  get_it: ^6.0.0
  rxdart: ^0.26.0
  bloc_pattern: ^2.5.1
  shared_preferences: ^2.0.3
  flutter_svg: ^0.19.3
  firebase_storage: ^8.0.0
  google_sign_in: ^5.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  hive: ^1.4.4+1
  dio: ^4.0.0-beta7
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  http_parser: ^4.0.0
  analyzer: ^0.39.1
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^5.0.0
  mobx_codegen: ^1.1.2
  effective_dart: ^1.3.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Google
      fonts: 
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
