name: financialcontroleeapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  fluttertoast: ^8.0.3
  flutter_easyloading: ^3.0.0
  form_field_validator: ^1.1.0
  currency_text_input_formatter: ^2.0.1
  syncfusion_flutter_datepicker: ^19.1.54-beta.1
  json_annotation: ^4.0.0-nullsafety.0
  uuid: ^3.0.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  intl: ^0.17.0-nullsafety.2
  money2: ^2.0.2
  flutter_login_facebook: ^1.0.1
  # progress_dialog: ^1.2.4
  loading_animations: ^2.1.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  hasura_connect: ^3.0.0-nullsafety.0
  hasura_cache_interceptor: ^1.0.0-dev.5
  shared_preferences_cache_interceptor: ^1.0.0-dev.4
  # circular_check_box: ^1.0.4
  percent_indicator: ^3.3.0-nullsafety.1
  adaptive_dialog: ^0.10.0+5
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.2
  flutter_animation_progress_bar: ^2.0.0
  get_it: ^6.0.0
  rxdart: ^0.26.0
  bloc: ^7.0.0-nullsafety.0
  # bloc_pattern: ^2.5.1
  shared_preferences: ^2.0.3
  flutter_svg: ^0.21.0-nullsafety.0
  firebase_storage: ^8.0.1
  google_sign_in: ^5.0.1
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.0-1.0.nullsafety.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  dio: ^4.0.0-beta7
  flutter_mobx: ^2.0.0
  mobx: ^2.0.0
  http_parser: ^4.0.0
  analyzer: ^1.3.0
  flutter_modular: ^3.0.0-nullsafety.46
  convert: ^3.0.0
  xml: ^5.0.0
  http: ^0.13.0-nullsafety.0
  flutter_modular_test: ^1.0.0-nullsafety.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dev_dependencies:
  mockito: ^5.0.0
  mobx_codegen: ^2.0.0
  effective_dart: ^1.3.0
  build_runner: ^1.12.2
  json_serializable: ^4.0.0-nullsafety.0
  # hive_generator: ^1.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
flutter_intl:
  enabled: true
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/app/core/localization/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/app/core/localization/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false


# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
